import { config as loadEnv } from "dotenv";
import { z } from "zod";

const EnvironmentSchema = z.object({
  CONVEX_URL: z.string().url().optional(),
  LMSTUDIO_BASE_URL: z.string().url().default("http://127.0.0.1:1234/v1"),
  LMSTUDIO_EMBED_MODEL: z.string().default("text-embedding-embeddinggemma-300m-qat"),
  OPENBRAIN_API_HOST: z.string().default("127.0.0.1"),
  OPENBRAIN_API_PORT: z
    .string()
    .default("8787")
    .transform((value) => Number.parseInt(value, 10))
    .pipe(z.number().int().min(1).max(65535)),
});

export type OpenBrainConfig = {
  convexUrl: string;
  lmStudioBaseUrl: string;
  lmStudioEmbedModel: string;
  apiHost: string;
  apiPort: number;
};

export function loadEnvironment(): void {
  // Priority order: .env then .env.local overrides.
  loadEnv({ path: ".env", quiet: true });
  loadEnv({ path: ".env.local", override: true, quiet: true });
}

export function parseEnvironment(env: NodeJS.ProcessEnv): OpenBrainConfig {
  const parsed = EnvironmentSchema.safeParse(env);
  if (!parsed.success) {
    throw new Error(`Invalid environment: ${parsed.error.message}`);
  }

  const { CONVEX_URL, LMSTUDIO_BASE_URL, LMSTUDIO_EMBED_MODEL, OPENBRAIN_API_HOST, OPENBRAIN_API_PORT } =
    parsed.data;

  if (!CONVEX_URL) {
    throw new Error("CONVEX_URL is required. Use .env.local generated by Convex or set it manually.");
  }

  return {
    convexUrl: CONVEX_URL,
    lmStudioBaseUrl: LMSTUDIO_BASE_URL.replace(/\/+$/, ""),
    lmStudioEmbedModel: LMSTUDIO_EMBED_MODEL,
    apiHost: OPENBRAIN_API_HOST,
    apiPort: OPENBRAIN_API_PORT,
  };
}

export function getConfig(): OpenBrainConfig {
  loadEnvironment();
  return parseEnvironment(process.env);
}
